// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type User struct {
	ID        interface{}
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
