import type {Metadata} from "next";
import type {ReactNode} from "react";

import {cn} from "@/helpers/ui";
import {Inter} from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({children}: { children: ReactNode }) => {
    return (
        <html lang="en" className="light">
        <body
            className={cn(
                "min-h-screen font-sans antialiased grainy",
                inter.className
            )}
        >
        <Navbar/>
        {children}
        </body>
        </html>
    );
};

export default RootLayout;
